### ISSUE TITLE
Implement basics CSS Styling

### ISSUE THREAD

**Issue by devidda** [devidda/isef#3]
### Feature Description
This feature involves implementing basic CSS styling for various components on the website.

### Estimated Effort
Medium

### Tasks

- [x] decide which CSS-framework we should use
- [x] implement it in the project so we can use it

### Acceptance criteria
CSS can be used by the developers

**Comment by devidda** [comment]
@KeiraShadow please make sure to **pull** the latest changes from develop into your branch before creating the pull request.
Or **rebase** instead, that's my personal favourite when I'm opening PRs.

**Comment by KeiraShadow** [comment]
ahh sorry I didn't realize

**Comment by devidda** [comment]
no need to apologize, I just wanted to note that here before the PR :)
